language: python

    python:

      - "2.7"

    env:

    - DJANGO_VERSION=1.9.7

    services:

    - postgresql

    install:

      - pip install -r requirements.txt

    script:

      - python manage.py test
