version: '3.3'

services:
 # Postgres
 db:
   image: postgres
   environment:
     - POSTGRES_USER=takwimu
     - POSTGRES_PASSWORD=takwimu
     - POSTGRES_DB=takwimu

 web:
   build: .
   command: ["./run_web.sh"]
   volumes:
     - .:/webapps
   ports:
     - "8000:8000"
   links:
     - db
   depends_on:
     - db